//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscanerExpedientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoUsuario
    {
        public EstadoUsuario()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdEstado { get; set; }
        public string EstadoUsuario1 { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
