//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscanerExpedientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoja
    {
        public int IdHoja { get; set; }
        public byte[] HojaAgregada { get; set; }
        public Nullable<int> usuarioCreo { get; set; }
        public Nullable<int> usuarioModificado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaModificado { get; set; }
    }
}
